version: "3"
services:
 frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true